/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provaindividual;

/**
 *
 * @author julia
 */
public class SimuladorFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorFinanceiro
     */
    public SimuladorFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfQuantidade1 = new javax.swing.JTextField();
        tfPrecoDaUnidade1 = new javax.swing.JTextField();
        tfMetros1 = new javax.swing.JTextField();
        lblTitulo1 = new javax.swing.JLabel();
        btnCalculo1 = new javax.swing.JButton();
        lblPergunta1 = new javax.swing.JLabel();
        lblPergunta2 = new javax.swing.JLabel();
        lblPergunta3 = new javax.swing.JLabel();
        lblContexto1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTexto1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setForeground(java.awt.Color.darkGray);

        tfQuantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidade1ActionPerformed(evt);
            }
        });

        tfPrecoDaUnidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoDaUnidade1ActionPerformed(evt);
            }
        });

        lblTitulo1.setText("Simulador Financeiro ");

        btnCalculo1.setText("Calcular");
        btnCalculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculo1ActionPerformed(evt);
            }
        });

        lblPergunta1.setText("Qual a quantidade de produtos?");

        lblPergunta2.setText("Qual o custo médio unitário?");

        lblPergunta3.setText("Qual o tamanho do armazém por m²?");

        lblContexto1.setText("Saiba o quanto você vai economizar investindo na nossa solução de armazenamento monitorado");

        taTexto1.setColumns(20);
        taTexto1.setRows(5);
        jScrollPane1.setViewportView(taTexto1);

        jLabel1.setText("o o controle de temperatura no seu armazém de cervejas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPergunta1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfQuantidade1)
                        .addComponent(tfMetros1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPergunta2)
                    .addComponent(tfPrecoDaUnidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculo1)
                    .addComponent(lblPergunta3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContexto1)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContexto1)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPergunta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblPergunta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPrecoDaUnidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPergunta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMetros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculo1))
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPrecoDaUnidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoDaUnidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoDaUnidade1ActionPerformed

    private void tfQuantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidade1ActionPerformed

    private void btnCalculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculo1ActionPerformed
Double quantidade = Double.valueOf(tfQuantidade1.getText());
Double precoDaUnidade = Double.valueOf(tfPrecoDaUnidade1.getText());
Double metro = Double.valueOf(tfMetros1.getText());

// Pegar o valor total de todos os produtos
Double valorTotalProdutos = quantidade * precoDaUnidade;

// Por falta de controle do armazém tem uma perca de 25% de produtos.
Double percasEmUmMes = valorTotalProdutos * 25 / 100 ;

// Total de percas em um ano
Double percasEmUmAno = percasEmUmMes * 12;

// 50 é o valor por m² pelo serviço de moitoramento em um mês
Double precoPorMesM2 = metro * 50;

//Valor do serviço em um ano 
Double precoPorAnoM2 = precoPorMesM2 * 12 ;

//Quantia 



taTexto1.setText(String.format("No seu armazém, você possuí um total de R$%.2f \n em cervejas.  Com a falta de monitoramento e controle\n de temperatura no seu armazém de cerveja, você está\n sujeito a ter um percentual de 15%% de suas mercadorias\n perdidas.  Um total de R$%.2f  em um mês,\n R$%.2f ao ano. \n\n Com a nossa solução que custa R$50,00 por M², você\n vai investir R$%.2f no mês e R$%.2f em um\n ano!! Não perca essa oportunidade!",
        valorTotalProdutos, percasEmUmMes,percasEmUmAno, precoPorMesM2, precoPorAnoM2));
    }//GEN-LAST:event_btnCalculo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContexto1;
    private javax.swing.JLabel lblPergunta1;
    private javax.swing.JLabel lblPergunta2;
    private javax.swing.JLabel lblPergunta3;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextArea taTexto1;
    private javax.swing.JTextField tfMetros1;
    private javax.swing.JTextField tfPrecoDaUnidade1;
    private javax.swing.JTextField tfQuantidade1;
    // End of variables declaration//GEN-END:variables
}
